name: benchmark-system-gb

channels:
  - conda-forge
  - defaults

dependencies:
  - django=4.0.3
  - djangorestframework=3.13.1
  - python=3.9.12
  - pandas=1.4.2
  - wetterdienst=0.31.1
  - pgeocode=0.3.0
  - pip=22.1.1
  - pip:
      - django-rest-knox==4.2.0