name: benchmark-system-gb

channels:
  - conda-forge
  - defaults

dependencies:
  - django=4.0.3
  - djangorestframework=3.13.1
  - python=3.9.12
  - pandas=1.4.2
  - wetterdienst=0.31.1
  - psycopg2=2.9.3
  - openpyxl=3.0.9
  - numpy=1.22.3
  - pip=22.1.1
  - django-environ=0.9.0
  - pip:
      - django-rest-knox==4.2.0